import {Injectable} from '@angular/core';
import {DAILY, Day, Rating, WEEKEND} from "../app/declarations";
import {ARCHITEKTUR, ATTRAKTION, BAHN, BIER, BLUMEN, BOGENSCHIESSEN, EISLAUFEN, ERLEBNISWELT, GESCHICHTE, HOEHLE, KLETTERGARTEN, KLETTERN, KUNST, MINIGOLF, MUSEUM, NATURAKTIVITAET, PARK, RELIGION, RIDING, SCHIFF, SCHLOSS, SCHNAPS, SCHWIMMEN, SKI, SOMMERRODELBAHN, STADTRUNDGANG, TECHNIK, TRAMPOLIN, VERKEHR, WANDERN, WEIN, ZOO} from "./TAGS";

const ratings: {
    [key: string]: Rating
} = {
    "1265": {rating: 1, tag: [BAHN, NATURAKTIVITAET, WANDERN], district: "NK", opening: [{from: "2025-04-26", to: "2025-11-02", days: DAILY}]},
    "1010": {rating: 2, tag: [BLUMEN], district: "KR", opening: [{from: "2025-03-15", to: "2025-10-31", days:DAILY}, {from: "2025-11-02", to: "2026-01-06", days: DAILY}]},
    "1394": {rating: 1, tag: [ATTRAKTION], district: "W", opening: [{from: "2025-02-01", to: "2026-01-06", days: DAILY}]},
    "1190": {rating: 2, tag: [NATURAKTIVITAET, WANDERN], district: "NK"},
    "826": {rating: 2, tag: [BLUMEN], district: "TU"},
    "18692": {rating: 2, tag: [SCHLOSS], district: "GF"},
    "1295": {rating: 1, tag: [ATTRAKTION, SOMMERRODELBAHN], district: "W"},
    "838": {rating: 2, tag: [ATTRAKTION], district: "WB"},
    "1067": {rating: 2, tag: [NATURAKTIVITAET, WANDERN], district: "BM"},
    "1196": {rating: 3, tag: [SCHLOSS], district: "ME"},
    "1343": {rating: 3, tag: [ZOO], district: "AM"},
    "1289": {rating: 4, tag: [SCHWIMMEN], district: "GM"},
    "1138": {rating: 1, tag: [PARK], district: "MD", opening: [{from: "2025-03-29", to: "2025-11-02", days: DAILY}]},
    "1210": {rating: 1, tag: [MUSEUM], district: "BL"},
    "1414": {rating: 3, tag: [ZOO], district: "W"},
    "1293": {rating: 1, tag: [ATTRAKTION, SOMMERRODELBAHN], district: "NK"},
    "1212": {rating: 4, tag: [SCHWIMMEN], district: "BN"},
    "719": {rating: 1, tag: [MUSEUM], district: "HL"},
    "789": {rating: 1, tag: [NATURAKTIVITAET, WANDERN, RIDING], district: "NK"},
    "932563": {rating: 2, tag: [NATURAKTIVITAET, BOGENSCHIESSEN], district: "SB"},
    "1246": {rating: 3, tag: [MUSEUM], district: "WY"},
    "707": {rating: 3, tag: [NATURAKTIVITAET, ZOO], district: "HL"},
    "710": {rating: 4, tag: [SCHWIMMEN], district: "SB"},
    "1301": {rating: 3, tag: [ZOO], district: "GD"},
    "721": {rating: 3, tag: [NATURAKTIVITAET, WANDERN], district: "LF"},
    "724": {rating: 2, tag: [MUSEUM], district: "WT"},
    "730": {rating: 4, tag: [SCHWIMMEN], district: "P"},
    "856": {rating: 4, tag: [SCHWIMMEN], district: "PL"},
    "734": {rating: 2, tag: [SCHLOSS], district: "LF"},
    "293664": {rating: 1, tag: [MUSEUM, GESCHICHTE], district: "WB"},
    "743": {rating: 2, tag: [MUSEUM, ARCHITEKTUR], district: "BN"},
    "747": {rating: 4, tag: [SCHWIMMEN], district: "TU"},
    "750": {rating: 4, tag: [SCHWIMMEN], district: "ME"},
    "753": {rating: 3, tag: [PARK], district: "KO"},
    "755": {rating: 2, tag: [MUSEUM, KUNST], district: "KR"},
    "758": {rating: 2, tag: [MUSEUM], district: "ZT"},
    "763": {rating: 4, tag: [BAHN, SCHIFF], district: "KR"},
    "766": {rating: 2, tag: [MUSEUM], district: "NK"},
    "1192": {rating: 1, tag: [BAHN], district: "HL"},
    "771": {rating: 1, tag: [ZOO], district: "ZT"},
    "1234": {rating: 3, tag: [SCHLOSS], district: "ND"},
    "773": {rating: 3, tag: [MUSEUM], district: "BD"},
    "777": {rating: 1, tag: [MUSEUM, KUNST], district: "W"},
    "782": {rating: 3, tag: [MUSEUM, RELIGION], district: "KR"},
    "1327": {rating: 3, tag: [MUSEUM, RELIGION], district: "ME"},
    "787": {rating: 4, tag: [SCHWIMMEN], district: "BL"},
    "791": {rating: 2, tag: [MUSEUM, KUNST], district: "BN"},
    "794": {rating: 2, tag: [ERLEBNISWELT, TECHNIK], district: "ME"},
    "932566": {rating: 3, tag: [NATURAKTIVITAET, RIDING], district: "AM"},
    "18932": {rating: 3, tag: [ERLEBNISWELT], district: "WT"},
    "932633": {rating: 1, tag: [NATURAKTIVITAET, BOGENSCHIESSEN], district: "NK", opening: [{from: "2025-03-15", to: "2025-12-01", days: [Day.FR, Day.SA, Day.SO, Day.FE]}]},
    "932595": {rating: 1, tag: [ERLEBNISWELT, BIER], district: "SB"},
    "804": {rating: 3, tag: [SCHLOSS], district: "MA"},
    "806": {rating: 3, tag: [SCHLOSS], district: "MD"},
    "808": {rating: 3, tag: [SCHLOSS], district: "OP"},
    "811": {rating: 3, tag: [SCHLOSS], district: "ME"},
    "814": {rating: 4, tag: [SCHWIMMEN], district: "WB"},
    "932342": {rating: 1, tag: [NATURAKTIVITAET, WANDERN, SCHLOSS], district: "", opening: [{from: "2025-03-22", to: "2025-10-31", days: DAILY}]},
    "816": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "818": {rating: 2, tag: [MUSEUM, KUNST], district: ""},
    "820": {rating: 3, tag: [SCHIFF], district: ""},
    "822": {rating: 3, tag: [ERLEBNISWELT, ZOO], district: ""},
    "824": {rating: 2, tag: [ERLEBNISWELT, SCHNAPS], district: ""},
    "944": {rating: 1, tag: [MUSEUM], district: ""},
    "830": {rating: 2, tag: [MUSEUM, KUNST], district: ""},
    "956": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "833": {rating: 2, tag: [MUSEUM], district: ""},
    "702": {rating: 3, tag: [ERLEBNISWELT], district: ""},
    "18667": {rating: 2, tag: [MUSEUM, KUNST], district: ""},
    "713": {rating: 1, tag: [ATTRAKTION, SOMMERRODELBAHN], district: ""},
    "932641": {rating: 2, tag: [ERLEBNISWELT], district: ""},
    "840": {rating: 1, tag: [MUSEUM, VERKEHR], district: ""},
    "843": {rating: 1, tag: [MUSEUM, VERKEHR], district: ""},
    "293860": {rating: 1, tag: [MUSEUM], district: ""},
    "1099": {rating: 1, tag: [MUSEUM], district: ""},
    "849": {rating: 2, tag: [MUSEUM], district: ""},
    "728": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "914": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "938": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "862": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "864": {rating: 3, tag: [NATURAKTIVITAET], district: ""},
    "866": {rating: 2, tag: [NATURAKTIVITAET, WANDERN], district: ""},
    "868": {rating: 1, tag: [BAHN], district: ""},
    "885": {rating: 2, tag: [BAHN], district: ""},
    "870": {rating: 2, tag: [MUSEUM, KUNST], district: ""},
    "874": {rating: 2, tag: [MUSEUM], district: ""},
    "876": {rating: 3, tag: [MUSEUM], district: ""},
    "1226": {rating: 3, tag: [MUSEUM], district: ""},
    "883": {rating: 2, tag: [MUSEUM, VERKEHR], district: ""},
    "881": {rating: 2, tag: [MUSEUM, VERKEHR], district: ""},
    "887": {rating: 3, tag: [SKI], district: ""},
    "889": {rating: 2, tag: [ERLEBNISWELT, SCHNAPS], district: ""},
    "989": {rating: 3, tag: [MUSEUM], district: ""},
    "900": {rating: 2, tag: [ERLEBNISWELT], district: ""},
    "903": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "905": {rating: 1, tag: [ATTRAKTION, TRAMPOLIN], district: ""},
    "894": {rating: 1, tag: [ERLEBNISWELT], district: ""},
    "907": {rating: 3, tag: [MUSEUM], district: ""},
    "912": {rating: 1, tag: [MUSEUM, GESCHICHTE], district: ""},
    "858": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "715": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "920": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "922": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "847": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "924": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "926": {rating: 1, tag: [MUSEUM, GESCHICHTE], district: ""},
    "928": {rating: 1, tag: [MUSEUM, GESCHICHTE], district: ""},
    "930": {rating: 1, tag: [MUSEUM, GESCHICHTE], district: ""},
    "934": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "936": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "932546": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "940": {rating: 2, tag: [MUSEUM, KUNST], district: ""},
    "1285": {rating: 2, tag: [NATURAKTIVITAET, WANDERN, SKI], district: ""},
    "942": {rating: 2, tag: [MUSEUM, KUNST], district: ""},
    "1166": {rating: 1, tag: [MUSEUM], district: ""},
    "946": {rating: 4, tag: [NATURAKTIVITAET], district: ""},
    "948": {rating: 3, tag: [SCHLOSS], district: ""},
    "898": {rating: 2, tag: [MUSEUM], district: ""},
    "1144": {rating: 3, tag: [ERLEBNISWELT, ZOO], district: ""},
    "954": {rating: 2, tag: [MUSEUM], district: ""},
    "958": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "961": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "963": {rating: 2, tag: [MUSEUM], district: ""},
    "965": {rating: 2, tag: [MUSEUM], district: ""},
    "967": {rating: 4, tag: [ERLEBNISWELT, SCHWIMMEN], district: ""},
    "860": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "969": {rating: 2, tag: [ERLEBNISWELT, MUSEUM], district: ""},
    "293858": {rating: 1, tag: [MUSEUM], district: ""},
    "971": {rating: 1, tag: [MUSEUM], district: ""},
    "973": {rating: 1, tag: [MUSEUM], district: ""},
    "975": {rating: 2, tag: [MUSEUM], district: ""},
    "977": {rating: 3, tag: [MUSEUM], district: ""},
    "979": {rating: 2, tag: [MUSEUM], district: ""},
    "981": {rating: 4, tag: [MUSEUM], district: ""},
    "1267": {rating: 1, tag: [MUSEUM], district: ""},
    "983": {rating: 1, tag: [NATURAKTIVITAET, WANDERN, HOEHLE], district: "", opening: [
        {from: "2025-03-29", to: "2025-04-05", days: WEEKEND}, {from: "2025-04-12", to: "2025-04-21", days: DAILY}, "2025-04-26", "2025-04-27", {from: "2025-05-01", to: "2025-09-30", days: DAILY}, {from: "2025-10-01", to: "2025-11-02", days: WEEKEND}]},
    "18921": {rating: 1, tag: [BAHN], district: ""},
    "996": {rating: 3, tag: [SCHLOSS], district: ""},
    "293870": {rating: 1, tag: [MUSEUM], district: ""},
    "932629": {rating: 1, tag: [ATTRAKTION, TRAMPOLIN], district: ""},
    "18842": {rating: 3, tag: [MUSEUM], district: ""},
    "994": {rating: 1, tag: [MUSEUM, KUNST], district: ""},
    "1096770": {rating: 3, tag: [MUSEUM, RELIGION], district: ""},
    "1000": {rating: 3, tag: [MUSEUM, RELIGION], district: ""},
    "1002": {rating: 2, tag: [MUSEUM, ERLEBNISWELT], district: ""},
    "1006": {rating: 2, tag: [MUSEUM, KUNST], district: ""},
    "1408": {rating: 4, tag: [BAHN], district: ""},
    "1013": {rating: 2, tag: [ERLEBNISWELT, WEIN], district: ""},
    "1015": {rating: 2, tag: [KLETTERN], district: ""},
    "932631": {rating: 2, tag: [KLETTERN], district: ""},
    "932278": {rating: 2, tag: [KLETTERN], district: ""},
    "1017": {rating: 2, tag: [ERLEBNISWELT], district: ""},
    "1160": {rating: 3, tag: [MUSEUM, KUNST], district: ""},
    "932637": {rating: 4, tag: [MUSEUM, VERKEHR], district: ""},
    "1021": {rating: 2, tag: [MUSEUM, GESCHICHTE], district: ""},
    "1023": {rating: 4, tag: [ERLEBNISWELT], district: ""},
    "1025": {rating: 1, tag: [MUSEUM], district: ""},
    "1027": {rating: 3, tag: [MUSEUM], district: ""},
    "952": {rating: 2, tag: [MUSEUM], district: ""},
    "1029": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1033": {rating: 3, tag: [EISLAUFEN], district: ""},
    "1031": {rating: 3, tag: [EISLAUFEN], district: ""},
    "1035": {rating: 3, tag: [EISLAUFEN], district: ""},
    "18942": {rating: 3, tag: [EISLAUFEN], district: ""},
    "1037": {rating: 2, tag: [MUSEUM, KUNST], district: ""},
    "1040": {rating: 2, tag: [MUSEUM, VERKEHR], district: ""},
    "1259": {rating: 2, tag: [PARK], district: ""},
    "918": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1042": {rating: 2, tag: [MUSEUM, KUNST], district: ""},
    "1048": {rating: 3, tag: [MUSEUM], district: ""},
    "1050": {rating: 1, tag: [MUSEUM], district: ""},
    "1052": {rating: 1, tag: [SCHLOSS], district: ""},
    "1055": {rating: 4, tag: [ERLEBNISWELT, ZOO], district: ""},
    "1168": {rating: 1, tag: [MUSEUM], district: ""},
    "1057": {rating: 1, tag: [MUSEUM, WEIN], district: ""},
    "1059": {rating: 1, tag: [MUSEUM, KUNST], district: ""},
    "1061": {rating: 1, tag: [MUSEUM, GESCHICHTE], district: ""},
    "1063": {rating: 1, tag: [MUSEUM, GESCHICHTE], district: ""},
    "828": {rating: 2, tag: [MUSEUM, ATTRAKTION, MINIGOLF], district: ""},
    "1069": {rating: 2, tag: [MUSEUM], district: ""},
    "1071": {rating: 1, tag: [NATURAKTIVITAET], district: ""},
    "1073": {rating: 3, tag: [ATTRAKTION, MINIGOLF], district: ""},
    "769": {rating: 2, tag: [ATTRAKTION, MINIGOLF], district: ""},
    "1078": {rating: 1, tag: [ATTRAKTION, MINIGOLF], district: ""},
    "1076": {rating: 2, tag: [ATTRAKTION, MINIGOLF], district: ""},
    "1082": {rating: 1, tag: [MUSEUM, ERLEBNISWELT, VERKEHR], district: ""},
    "1084": {rating: 1, tag: [MUSEUM, ERLEBNISWELT, VERKEHR], district: ""},
    "1086": {rating: 1, tag: [ERLEBNISWELT], district: ""},
    "1088": {rating: 2, tag: [ERLEBNISWELT, SCHNAPS], district: ""},
    "1345": {rating: 3, tag: [NATURAKTIVITAET, RIDING], district: ""},
    "293872": {rating: 1, tag: [MUSEUM, KUNST], district: ""},
    "1095": {rating: 3, tag: [MUSEUM, RELIGION, KUNST], district: ""},
    "1101": {rating: 2, tag: [MUSEUM, KUNST], district: ""},
    "1103": {rating: 3, tag: [MUSEUM], district: ""},
    "1105": {rating: 2, tag: [MUSEUM, RELIGION], district: ""},
    "1107": {rating: 3, tag: [MUSEUM, SCHLOSS], district: ""},
    "1109": {rating: 2, tag: [MUSEUM], district: ""},
    "1162": {rating: 2, tag: [MUSEUM], district: ""},
    "1111": {rating: 2, tag: [MUSEUM], district: ""},
    "1113": {rating: 3, tag: [MUSEUM, RELIGION], district: ""},
    "1115": {rating: 3, tag: [MUSEUM], district: ""},
    "1117": {rating: 2, tag: [MUSEUM], district: ""},
    "1119": {rating: 2, tag: [MUSEUM], district: ""},
    "1122": {rating: 2, tag: [MUSEUM], district: ""},
    "1124": {rating: 1, tag: [MUSEUM], district: ""},
    "932639": {rating: 1, tag: [ERLEBNISWELT], district: ""},
    "1126": {rating: 1, tag: [NATURAKTIVITAET, WANDERN], district: ""},
    "932339": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1130": {rating: 1, tag: [NATURAKTIVITAET, WANDERN], district: ""},
    "1132": {rating: 2, tag: [NATURAKTIVITAET, WANDERN], district: ""},
    "1134": {rating: 1, tag: [NATURAKTIVITAET, WANDERN], district: ""},
    "1136": {rating: 1, tag: [NATURAKTIVITAET, WANDERN], district: ""},
    "932541": {rating: 3, tag: [ERLEBNISWELT], district: ""},
    "1140": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1142": {rating: 1, tag: [NATURAKTIVITAET, WANDERN, HOEHLE], district: ""},
    "1146": {rating: 1, tag: [MUSEUM], district: ""},
    "1150": {rating: 1, tag: [NATURAKTIVITAET, WANDERN], district: ""},
    "1152": {rating: 3, tag: [ATTRAKTION], district: ""},
    "1154": {rating: 1, tag: [MUSEUM, KUNST], district: ""},
    "293804": {rating: 2, tag: [BLUMEN], district: ""},
    "1158": {rating: 2, tag: [MUSEUM, VERKEHR], district: ""},
    "932": {rating: 3, tag: [MUSEUM], district: ""},
    "1044": {rating: 2, tag: [MUSEUM], district: ""},
    "1172": {rating: 1, tag: [NATURAKTIVITAET, WANDERN,HOEHLE], district: ""},
    "1174": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1287": {rating: 2, tag: [NATURAKTIVITAET, WANDERN], district: ""},
    "932635": {rating: 2, tag: [MUSEUM], district: ""},
    "916": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1176": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "852": {rating: 1, tag: [MUSEUM], district: ""},
    "1178": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "293829": {rating: 3, tag: [MUSEUM], district: ""},
    "932625": {rating: 4, tag: [ATTRAKTION], district: ""},
    "987": {rating: 3, tag: [MUSEUM], district: ""},
    "1180": {rating: 1, tag: [MUSEUM, KUNST], district: ""},
    "1164": {rating: 1, tag: [MUSEUM], district: ""},
    "1186": {rating: 2, tag: [MUSEUM], district: ""},
    "1194": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1355": {rating: 1, tag: [MUSEUM, VERKEHR], district: ""},
    "1230": {rating: 3, tag: [SCHLOSS], district: ""},
    "293642": {rating: 3, tag: [SCHLOSS], district: ""},
    "1198": {rating: 3, tag: [ZOO], district: ""},
    "1200": {rating: 1, tag: [ERLEBNISWELT], district: ""},
    "1204": {rating: 1, tag: [ATTRAKTION], district: ""},
    "1206": {rating: 1, tag: [MUSEUM], district: ""},
    "1097": {rating: 1, tag: [MUSEUM, GESCHICHTE], district: ""},
    "1214": {rating: 2, tag: [MUSEUM], district: ""},
    "293868": {rating: 2, tag: [NATURAKTIVITAET, KLETTERGARTEN], district: ""},
    "1216": {rating: 2, tag: [SCHLOSS], district: ""},
    "1220": {rating: 2, tag: [MUSEUM, RELIGION], district: ""},
    "1222": {rating: 2, tag: [SKI], district: ""},
    "1224": {rating: 2, tag: [MUSEUM], district: ""},
    "992": {rating: 2, tag: [SCHLOSS], district: ""},
    "1228": {rating: 3, tag: [SCHLOSS], district: ""},
    "18844": {rating: 3, tag: [SCHLOSS, PARK], district: ""},
    "1232": {rating: 3, tag: [SCHLOSS], district: ""},
    "1255": {rating: 1, tag: [SCHLOSS], district: ""},
    "18656": {rating: 2, tag: [SCHLOSS], district: ""},
    "18696": {rating: 2, tag: [SCHLOSS], district: ""},
    "1242": {rating: 2, tag: [SCHLOSS, MUSEUM], district: ""},
    "1244": {rating: 3, tag: [SCHLOSS], district: ""},
    "293866": {rating: 1, tag: [SCHLOSS], district: ""},
    "18607": {rating: 3, tag: [SCHLOSS], district: ""},
    "1248": {rating: 2, tag: [SCHLOSS, MUSEUM], district: ""},
    "1250": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1257": {rating: 1, tag: [SCHLOSS, NATURAKTIVITAET, WANDERN, PARK], district: ""},
    "1261": {rating: 1, tag: [ERLEBNISWELT, WEIN], district: ""},
    "932627": {rating: 4, tag: [ERLEBNISWELT, TECHNIK], district: ""},
    "1263": {rating: 3, tag: [MUSEUM], district: ""},
    "1184": {rating: 2, tag: [NATURAKTIVITAET, WANDERN, SKI], district: ""},
    "1271": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1273": {rating: 1, tag: [MUSEUM], district: ""},
    "1275": {rating: 1, tag: [MUSEUM, KUNST], district: ""},
    "1277": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1279": {rating: 2, tag: [NATURAKTIVITAET, WANDERN], district: ""},
    "1281": {rating: 1, tag: [NATURAKTIVITAET, WANDERN], district: ""},
    "1283": {rating: 1, tag: [MUSEUM], district: ""},
    "1019": {rating: 2, tag: [SKI], district: ""},
    "1291": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1297": {rating: 2, tag: [MUSEUM], district: ""},
    "1252": {rating: 2, tag: [MUSEUM], district: ""},
    "1299": {rating: 2, tag: [MUSEUM], district: ""},
    "932605": {rating: 1, tag: [ATTRAKTION, TRAMPOLIN], district: ""},
    "1307": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "293864": {rating: 3, tag: [MUSEUM], district: ""},
    "1311": {rating: 2, tag: [MUSEUM], district: ""},
    "1313": {rating: 3, tag: [MUSEUM], district: ""},
    "1315": {rating: 3, tag: [MUSEUM], district: ""},
    "1080": {rating: 1, tag: [STADTRUNDGANG], district: ""},
    "1317": {rating: 2, tag: [BLUMEN], district: ""},
    "293688": {rating: 2, tag: [MUSEUM, GESCHICHTE], district: ""},
    "779": {rating: 2, tag: [MUSEUM, RELIGION], district: ""},
    "1319": {rating: 3, tag: [MUSEUM, RELIGION], district: ""},
    "1321": {rating: 3, tag: [MUSEUM, RELIGION], district: ""},
    "1323": {rating: 3, tag: [MUSEUM, RELIGION], district: ""},
    "1325": {rating: 3, tag: [MUSEUM, RELIGION], district: ""},
    "1424": {rating: 3, tag: [MUSEUM, RELIGION], district: ""},
    "1329": {rating: 3, tag: [MUSEUM, RELIGION], district: ""},
    "1333": {rating: 1, tag: [MUSEUM, GESCHICHTE], district: ""},
    "1335": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1337": {rating: 4, tag: [ZOO], district: ""},
    "293818": {rating: 2, tag: [MUSEUM], district: ""},
    "1339": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1128": {rating: 3, tag: [ZOO], district: ""},
    "1347": {rating: 3, tag: [MUSEUM], district: ""},
    "1349": {rating: 2, tag: [MUSEUM], district: ""},
    "293262": {rating: 2, tag: [STADTRUNDGANG], district: ""},
    "1351": {rating: 2, tag: [ZOO], district: ""},
    "1353": {rating: 2, tag: [MUSEUM, GESCHICHTE], district: ""},
    "1357": {rating: 2, tag: [MUSEUM, WEIN], district: ""},
    "1359": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1361": {rating: 2, tag: [MUSEUM], district: ""},
    "1341": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1363": {rating: 1, tag: [BAHN], district: ""},
    "1365": {rating: 2, tag: [MUSEUM], district: ""},
    "1367": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1369": {rating: 3, tag: [MUSEUM], district: ""},
    "1371": {rating: 4, tag: [MUSEUM], district: ""},
    "1373": {rating: 2, tag: [ZOO], district: ""},
    "293856": {rating: 2, tag: [NATURAKTIVITAET, KLETTERGARTEN], district: ""},
    "1375": {rating: 1, tag: [BAHN], district: ""},
    "1377": {rating: 2, tag: [MUSEUM], district: ""},
    "1379": {rating: 3, tag: [MUSEUM], district: ""},
    "1381": {rating: 3, tag: [MUSEUM], district: ""},
    "985": {rating: 2, tag: [NATURAKTIVITAET, WANDERN], district: ""},
    "1383": {rating: 2, tag: [MUSEUM], district: ""},
    "1385": {rating: 4, tag: [SKI], district: ""},
    "892": {rating: 3, tag: [MUSEUM], district: ""},
    "1386": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1388": {rating: 2, tag: [MUSEUM], district: ""},
    "1390": {rating: 4, tag: [NATURAKTIVITAET, RIDING], district: ""},
    "1392": {rating: 2, tag: [ERLEBNISWELT, SCHNAPS], district: ""},
    "1396": {rating: 1, tag: [MUSEUM, ARCHITEKTUR], district: ""},
    "1398": {rating: 2, tag: [MUSEUM], district: ""},
    "1400": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "932276": {rating: 3, tag: [ZOO], district: ""},
    "932271": {rating: 2, tag: [MUSEUM], district: ""},
    "1202": {rating: 1, tag: [MUSEUM], district: ""},
    "1404": {rating: 4, tag: [MUSEUM, WEIN], district: ""},
    "1406": {rating: 3, tag: [MUSEUM], district: ""},
    "1410": {rating: 2, tag: [MUSEUM], district: ""},
    "1412": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "932308": {rating: 3, tag: [MUSEUM], district: ""},
    "1416": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "1418": {rating: 1, tag: [BAHN], district: ""},
    "1420": {rating: 2, tag: [MUSEUM, GESCHICHTE], district: ""},
    "1422": {rating: 2, tag: [MUSEUM], district: ""},
    "1331": {rating: 3, tag: [MUSEUM, RELIGION], district: ""},
    "1426": {rating: 4, tag: [SCHWIMMEN], district: ""},
    "293862": {rating: 2, tag: [STADTRUNDGANG], district: ""},
    "1238": {rating: 3, tag: [SCHLOSS], district: ""},
    "1309": {rating: 3, tag: [MUSEUM], district: ""},
    "1326031": {rating: 1, tag: [MUSEUM, KUNST], district: "TU"},
    "1326029": {rating: 2, tag: [ZOO], district: "WB"},
    "1326042": {rating: 2, tag: [ERLEBNISWELT, BLUMEN], district: "KR"},
    "1326024": {rating: 4, tag: [ATTRAKTION], district: "BM"},
    "1326025": {rating: 2, tag: [MUSEUM], district: "W"},
    "1326027": {rating: 2, tag: [KLETTERN], district: "WN"},
    "1326037": {rating: 2, tag: [WEIN], district: "HO"},
    "1326034": {rating: 2, tag: [BIER], district: "SB"},
    "1334001": {rating: 1, tag: [STADTRUNDGANG], district: "BL"},
    "1333902": {rating: 4, tag: [ATTRAKTION], district: "ZE"},
    "1326033": {rating: 1, tag: [MUSEUM, RELIGION], district: "P"},
    "1326041": {rating: 4, tag: [SCHWIMMEN], district: "GM"},
    "1326026": {rating: 2, tag: [MUSEUM, KUNST], district: "W"},
    "1326039": {rating: 4, tag: [ATTRAKTION], district: "HL"},
    "1326032": {rating: 4, tag: [MUSEUM, KUNST], district: "P"},
    "1326030": {rating: 1, tag: [NATURAKTIVITAET, KLETTERGARTEN], district: "TU"},
    "1326028": {rating: 2, tag: [ATTRAKTION, MINIGOLF], district: "NK"},
    "1326036": {rating: 2, tag: [KLETTERN], district: "MI"},
    "1326038": {rating: 2, tag: [MUSEUM, KUNST], district: "MI"},
    "1326035": {rating: 2, tag: [MUSEUM], district: "TU"},
    "1326040": {rating: 3, tag: [STADTRUNDGANG], district: "GM"},












}


@Injectable({
    providedIn: 'root'
})
export class RatingService {

    constructor() {
    }

    getRatingForId(id: number): Rating | null {
        return ratings[id] ?? null;
    }
}
